<?php
/*
Plugin Name: #Product Table Download Pdf
Plugin URI: https://www.haysky.com/
Description: This plugin code is generated by Haysky Code Generator.
Version: 1.0.0
Author: Sufyan
Author URI: https://www.sufyan.in/
License: GPLv2 or later
Text Domain: haysky
*/
// $wpdb->show_errors(); $wpdb->print_error();
error_reporting(E_ERROR | E_PARSE);

add_action( "init",function(){
    // Set labels for brand
    $labels = array(
        "name" => "Brands",
        "singular_name" => "Brand",
        "add_new"    => "Add Brand",
        "add_new_item" => "Add New Brand",
        "all_items" => "All Brands",
    );
    // Set Options for brand
    $args = array(    
        "labels"      => $labels,
        "hierarchical"               => true,
        "public"                     => true,
        "show_ui"                    => true,
        "show_admin_column"          => true,
        "show_in_nav_menus"          => true,
        "show_tagcloud"              => true,
        "show_in_rest"               => true,
    );
    register_taxonomy("brand", array("product"), $args);
    
});

if (isset($_GET["product_table_download_pdf"])) {
	if ($_GET['product_table_download_pdf']=='yes') {
		include 'pdf.php';
	}
}


$plugin = plugin_basename(__FILE__);
add_filter("plugin_action_links_$plugin",function($links){
    $product_table_download_pdf_button_link = 
    '<a href="'.site_url().'/?product_table_download_pdf=yes">Download PDF</a>';
    array_unshift($links, $product_table_download_pdf_button_link);
    return $links;
});

/* -- Creating all shortcodes -- */
add_shortcode('product_table_download_pdf_button',function(){
	return '<button><a href="'.site_url().'/?product_table_download_pdf=yes">Download PDF</a></button>';
});